---
layout: cv
title: Isabella Costello's CV
---
# Isabella Costello
Biology, Bioinformatics

<div id="webaddress">
<a href="cos24013@byui.edu">isaac@applesdofall.org</a>
</div>


## Currently

Completing Bachelors of Scince

### Specialized in

Bioinformatics, genetic information, data programming


### Research interests

Genomic information, protein structure, epigenetics and gene modification, biochemical pathways.


## Education

`2021-2025`
__California State Polytechnic University, Pomona__

`2025-2026`
__Brigham Young University, Idaho__



## Skills

`Bioinformatics`
- Sequence Alignment, BLAST, Phylogenetic Analysis, Database access
`Data Analysis` 
- R studio, Python, SQL
`Lab work `
- PCR, Gel Electrophoresis, Affinity Chromatography, Application of CRISPR technology


## Projects

`Meta-Analysis of Genes Affecting PCOS`
__Bioinformatics - Fall 2025__

- BLAST search, MSA, GWAS, Protein Structure Modelling
- DEG analysis, Ref Seq data, Enrichment

`Analysis of Probability of Genetic Deafness by Sex in Indonesia`
Intermediate Statistics - Spring 2025
- R Studio; Data Cleaning, Simple Logistic Regression, ggplot2, HTML knitting


`Analysis of Diagnosis Factors of Fragile X Syndrome in Ecuador`
Intermediate Statistics - Spring 2025
- R Studio; Data Cleaning, Multiple Logistic Regression, ggplot2, HTML knitting


`Column Chromatography`
Organic Chemistry - Fall 2024
- Preparation of the chromatography column, manipulating polarity, analyze eluent by Thin Layer Chromatography

`Insertion and Replication of Human Insulin Gene in E. Coli`
Phi Delta Research Society - Winter 2025

<!-- ### Footer

Last updated: December 2025 -->